# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'

target 'ExelbidSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExelbidSample

  pod 'ExelBid_iOS', '~> 1.3.16'
  pod 'AdFitSDK', '~> 3.12.18'

end
